### ISSUE TITLE
Migrate to latest version of operator-sdk

### ISSUE THREAD

**Issue by PhilipGough** [3scale/ostia#51]
The operator-sdk just moved the project to using container-runtime. There is a migration document in place which we should follow to here.

https://github.com/operator-framework/operator-sdk/blob/v0.1.0/doc/migration/v0.1.0-migration-guide.md

**Comment by mikz** [comment]
Might be easier at this point to just start from scratch? I guess there was plenty of changes in the last months.

**Comment by PhilipGough** [comment]
Could well be. You guys have been working with the sdk so in a best place to make that call. Leave this open to track?
